web:
        image: nginx
        ports:
                - "80:80"
        volumes:
                - ${VOLUME_NAME}:/nginx-PHP-fpm-web-server-router
        command: /bin/bash -c "cp /nginx-PHP-fpm-web-server-router/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        links:
                - php
php:
        image: php:fpm
        volumes:
                - ${VOLUME_NAME}:/nginx-PHP-fpm-web-server-router
